# Generated by Django 3.1.4 on 2020-12-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=500)),
                ('task_status', models.BooleanField(default=False)),
                ('task_date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
